AllCops:
  Include:
    - '**/*.rb'
    - 'Gemfile'
    - 'fastlane/*file'
    - 'iosApp/Podfile'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'fastlane/Fastfile'

Naming/FileName:
  Exclude:
    - 'fastlane/*file'

Style/Documentation:
  Enabled: false
