disabled_rules:
  # SwiftFormat puts trailing commas in collection literals sometimes
  - trailing_comma
excluded:
  - Pods

identifier_name:
  excluded:
    # allow implementing SKIE internal async methods from interfaces
    - "__.*"
