# frozen_string_literal: true

platform :ios, '15.0'

target 'iosApp' do
  project 'iosApp', 'Prod Debug' => :debug, 'Staging Debug' => :debug, 'DevOrange Debug' => :debug,
                    'Prod Release' => :release, 'Staging Release' => :release, 'DevOrange Release' => :release
  use_frameworks!
  pod 'shared', path: '../shared/'

  target 'iosAppTests' do
    inherit! :search_paths
  end
end
