platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!
  pod 'shared', :path => '../shared/'

  target 'iosAppTests' do
    inherit! :search_paths
    pod 'sharedTestUtil', :path => '../sharedTestUtil/'
  end
end
