package com.mbta.tid.mbta_app.android.generated

import com.mbta.tid.mbta_app.android.R

fun drawableByName(name: String): Int =
    when (name) {
        "alert-borderless-issue" -> R.drawable.alert_borderless_issue
        "alert-borderless-shuttle" -> R.drawable.alert_borderless_shuttle
        "alert-borderless-suspension" -> R.drawable.alert_borderless_suspension
        "alert-large-blue-issue" -> R.drawable.alert_large_blue_issue
        "alert-large-blue-shuttle" -> R.drawable.alert_large_blue_shuttle
        "alert-large-blue-suspension" -> R.drawable.alert_large_blue_suspension
        "alert-large-bus-issue" -> R.drawable.alert_large_bus_issue
        "alert-large-bus-shuttle" -> R.drawable.alert_large_bus_shuttle
        "alert-large-bus-suspension" -> R.drawable.alert_large_bus_suspension
        "alert-large-commuter-issue" -> R.drawable.alert_large_commuter_issue
        "alert-large-commuter-shuttle" -> R.drawable.alert_large_commuter_shuttle
        "alert-large-commuter-suspension" -> R.drawable.alert_large_commuter_suspension
        "alert-large-ferry-issue" -> R.drawable.alert_large_ferry_issue
        "alert-large-ferry-shuttle" -> R.drawable.alert_large_ferry_shuttle
        "alert-large-ferry-suspension" -> R.drawable.alert_large_ferry_suspension
        "alert-large-green-issue" -> R.drawable.alert_large_green_issue
        "alert-large-green-shuttle" -> R.drawable.alert_large_green_shuttle
        "alert-large-green-suspension" -> R.drawable.alert_large_green_suspension
        "alert-large-mattapan-issue" -> R.drawable.alert_large_mattapan_issue
        "alert-large-mattapan-shuttle" -> R.drawable.alert_large_mattapan_shuttle
        "alert-large-mattapan-suspension" -> R.drawable.alert_large_mattapan_suspension
        "alert-large-orange-issue" -> R.drawable.alert_large_orange_issue
        "alert-large-orange-shuttle" -> R.drawable.alert_large_orange_shuttle
        "alert-large-orange-suspension" -> R.drawable.alert_large_orange_suspension
        "alert-large-red-issue" -> R.drawable.alert_large_red_issue
        "alert-large-red-shuttle" -> R.drawable.alert_large_red_shuttle
        "alert-large-red-suspension" -> R.drawable.alert_large_red_suspension
        "alert-large-silver-issue" -> R.drawable.alert_large_silver_issue
        "alert-large-silver-shuttle" -> R.drawable.alert_large_silver_shuttle
        "alert-large-silver-suspension" -> R.drawable.alert_large_silver_suspension
        "alert-small-blue-issue" -> R.drawable.alert_small_blue_issue
        "alert-small-blue-shuttle" -> R.drawable.alert_small_blue_shuttle
        "alert-small-blue-suspension" -> R.drawable.alert_small_blue_suspension
        "alert-small-bus-issue" -> R.drawable.alert_small_bus_issue
        "alert-small-bus-shuttle" -> R.drawable.alert_small_bus_shuttle
        "alert-small-bus-suspension" -> R.drawable.alert_small_bus_suspension
        "alert-small-commuter-issue" -> R.drawable.alert_small_commuter_issue
        "alert-small-commuter-shuttle" -> R.drawable.alert_small_commuter_shuttle
        "alert-small-commuter-suspension" -> R.drawable.alert_small_commuter_suspension
        "alert-small-ferry-issue" -> R.drawable.alert_small_ferry_issue
        "alert-small-ferry-shuttle" -> R.drawable.alert_small_ferry_shuttle
        "alert-small-ferry-suspension" -> R.drawable.alert_small_ferry_suspension
        "alert-small-green-issue" -> R.drawable.alert_small_green_issue
        "alert-small-green-shuttle" -> R.drawable.alert_small_green_shuttle
        "alert-small-green-suspension" -> R.drawable.alert_small_green_suspension
        "alert-small-mattapan-issue" -> R.drawable.alert_small_mattapan_issue
        "alert-small-mattapan-shuttle" -> R.drawable.alert_small_mattapan_shuttle
        "alert-small-mattapan-suspension" -> R.drawable.alert_small_mattapan_suspension
        "alert-small-orange-issue" -> R.drawable.alert_small_orange_issue
        "alert-small-orange-shuttle" -> R.drawable.alert_small_orange_shuttle
        "alert-small-orange-suspension" -> R.drawable.alert_small_orange_suspension
        "alert-small-red-issue" -> R.drawable.alert_small_red_issue
        "alert-small-red-shuttle" -> R.drawable.alert_small_red_shuttle
        "alert-small-red-suspension" -> R.drawable.alert_small_red_suspension
        "alert-small-silver-issue" -> R.drawable.alert_small_silver_issue
        "alert-small-silver-shuttle" -> R.drawable.alert_small_silver_shuttle
        "alert-small-silver-suspension" -> R.drawable.alert_small_silver_suspension
        "fa-chevron-down" -> R.drawable.fa_chevron_down
        "fa-chevron-left" -> R.drawable.fa_chevron_left
        "fa-chevron-right" -> R.drawable.fa_chevron_right
        "fa-chevron-up" -> R.drawable.fa_chevron_up
        "fa-circle-info" -> R.drawable.fa_circle_info
        "fa-clock" -> R.drawable.fa_clock
        "fa-location-arrow-solid" -> R.drawable.fa_location_arrow_solid
        "fa-magnifying-glass-solid" -> R.drawable.fa_magnifying_glass_solid
        "fa-route" -> R.drawable.fa_route
        "fa-xmark" -> R.drawable.fa_xmark
        "live-data" -> R.drawable.live_data
        "location-dot" -> R.drawable.location_dot
        "location-halo" -> R.drawable.location_halo
        "map-nearby-location-cursor" -> R.drawable.map_nearby_location_cursor
        "map-stop-close-BLUE" -> R.drawable.map_stop_close_blue
        "map-stop-close-BUS" -> R.drawable.map_stop_close_bus
        "map-stop-close-BUS-transfer" -> R.drawable.map_stop_close_bus_transfer
        "map-stop-close-COMMUTER" -> R.drawable.map_stop_close_commuter
        "map-stop-close-FERRY" -> R.drawable.map_stop_close_ferry
        "map-stop-close-GREEN" -> R.drawable.map_stop_close_green
        "map-stop-close-GREEN-Green-B" -> R.drawable.map_stop_close_green_green_b
        "map-stop-close-GREEN-Green-C" -> R.drawable.map_stop_close_green_green_c
        "map-stop-close-GREEN-Green-D" -> R.drawable.map_stop_close_green_green_d
        "map-stop-close-GREEN-Green-E" -> R.drawable.map_stop_close_green_green_e
        "map-stop-close-MATTAPAN" -> R.drawable.map_stop_close_mattapan
        "map-stop-close-ORANGE" -> R.drawable.map_stop_close_orange
        "map-stop-close-RED" -> R.drawable.map_stop_close_red
        "map-stop-close-SILVER" -> R.drawable.map_stop_close_silver
        "map-stop-close-SILVER-741" -> R.drawable.map_stop_close_silver_741
        "map-stop-close-SILVER-742" -> R.drawable.map_stop_close_silver_742
        "map-stop-close-SILVER-743" -> R.drawable.map_stop_close_silver_743
        "map-stop-close-SILVER-746" -> R.drawable.map_stop_close_silver_746
        "map-stop-close-SILVER-749" -> R.drawable.map_stop_close_silver_749
        "map-stop-close-SILVER-751" -> R.drawable.map_stop_close_silver_751
        "map-stop-container-close-2" -> R.drawable.map_stop_container_close_2
        "map-stop-container-close-3" -> R.drawable.map_stop_container_close_3
        "map-stop-container-wide-2" -> R.drawable.map_stop_container_wide_2
        "map-stop-container-wide-3" -> R.drawable.map_stop_container_wide_3
        "map-stop-dummy-tap-pixel" -> R.drawable.map_stop_dummy_tap_pixel
        "map-stop-pin" -> R.drawable.map_stop_pin
        "map-stop-wide-BLUE" -> R.drawable.map_stop_wide_blue
        "map-stop-wide-BLUE-terminal" -> R.drawable.map_stop_wide_blue_terminal
        "map-stop-wide-BUS" -> R.drawable.map_stop_wide_bus
        "map-stop-wide-BUS-terminal" -> R.drawable.map_stop_wide_bus_terminal
        "map-stop-wide-BUS-transfer" -> R.drawable.map_stop_wide_bus_transfer
        "map-stop-wide-COMMUTER" -> R.drawable.map_stop_wide_commuter
        "map-stop-wide-COMMUTER-terminal" -> R.drawable.map_stop_wide_commuter_terminal
        "map-stop-wide-FERRY" -> R.drawable.map_stop_wide_ferry
        "map-stop-wide-FERRY-terminal" -> R.drawable.map_stop_wide_ferry_terminal
        "map-stop-wide-GREEN" -> R.drawable.map_stop_wide_green
        "map-stop-wide-GREEN-terminal-Green-B" -> R.drawable.map_stop_wide_green_terminal_green_b
        "map-stop-wide-GREEN-terminal-Green-C" -> R.drawable.map_stop_wide_green_terminal_green_c
        "map-stop-wide-GREEN-terminal-Green-D" -> R.drawable.map_stop_wide_green_terminal_green_d
        "map-stop-wide-GREEN-terminal-Green-E" -> R.drawable.map_stop_wide_green_terminal_green_e
        "map-stop-wide-MATTAPAN" -> R.drawable.map_stop_wide_mattapan
        "map-stop-wide-MATTAPAN-terminal" -> R.drawable.map_stop_wide_mattapan_terminal
        "map-stop-wide-ORANGE" -> R.drawable.map_stop_wide_orange
        "map-stop-wide-ORANGE-terminal" -> R.drawable.map_stop_wide_orange_terminal
        "map-stop-wide-RED" -> R.drawable.map_stop_wide_red
        "map-stop-wide-RED-terminal" -> R.drawable.map_stop_wide_red_terminal
        "map-stop-wide-SILVER" -> R.drawable.map_stop_wide_silver
        "map-stop-wide-SILVER-terminal" -> R.drawable.map_stop_wide_silver_terminal
        "map-stop-wide-SILVER-terminal-741" -> R.drawable.map_stop_wide_silver_terminal_741
        "map-stop-wide-SILVER-terminal-742" -> R.drawable.map_stop_wide_silver_terminal_742
        "map-stop-wide-SILVER-terminal-743" -> R.drawable.map_stop_wide_silver_terminal_743
        "map-stop-wide-SILVER-terminal-746" -> R.drawable.map_stop_wide_silver_terminal_746
        "map-stop-wide-SILVER-terminal-749" -> R.drawable.map_stop_wide_silver_terminal_749
        "map-stop-wide-SILVER-terminal-751" -> R.drawable.map_stop_wide_silver_terminal_751
        "mode-bus" -> R.drawable.mode_bus
        "mode-cr" -> R.drawable.mode_cr
        "mode-ferry" -> R.drawable.mode_ferry
        "mode-subway" -> R.drawable.mode_subway
        "pinned-route-active" -> R.drawable.pinned_route_active
        "pinned-route-inactive" -> R.drawable.pinned_route_inactive
        "vehicle-halo" -> R.drawable.vehicle_halo
        "vehicle-puck" -> R.drawable.vehicle_puck
        else -> throw IllegalArgumentException("Invalid drawable name $name")
    }
