disabled_rules:
  - file_length
  - function_body_length
  - type_body_length

identifier_name:
  excluded:
    - "id"
    # allow implementing SKIE internal async methods from interfaces
    - "__.*"
