# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

setup_ci if ENV['CI']

platform :android do
  desc "Deploy a new version to Google Play for internal testing"
  lane :internal do |options|
    version_codes = google_play_track_version_codes(
      track: "internal",
    )
    sh(
      "flutter", "build", "appbundle",
      "--dart-define", "SENTRY_DSN=" + (ENV['SENTRY_DSN'] || ''),
      "--dart-define", "SENTRY_ENVIRONMENT=" + (ENV['SENTRY_ENVIRONMENT'] || ''),
      "--build-number", (version_codes.max + 1).to_s
    )
    upload_to_play_store(
      # in either a fastlane bug or an Android Publisher API bug, until the app is reviewed and in alpha,
      # only draft releases can be created - https://github.com/fastlane/fastlane/discussions/18293
      release_status: "draft",
      track: "internal",
      aab: "build/app/outputs/bundle/release/app-release.aab",
      validate_only: options[:validate_only],
    )
  end
end
