name: Android staging deploy

on:
  push:
    branches:
      - main

jobs:
  build-android:
    name: Build for Android
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/build-android.yaml
    with:
      build-type: "Release"
      deploy: true
      flavor: "Staging"
      sentry-environment: "staging"
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GOOGLE_APP_ID_ANDROID: ${{ secrets.GOOGLE_APP_ID_ANDROID_STAGING }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_DSN_ANDROID: ${{ secrets.SENTRY_DSN_ANDROID }}
