name: iOS tests

on:
  workflow_call:
    inputs:
      skip-everything:
        description: "Skips all the individual steps so the job passes quickly"
        required: false
        default: false
        type: boolean
    secrets:
      SENTRY_DSN:
        required: true
      FIREBASE_KEY:
        required: true
      GOOGLE_APP_ID_IOS:
        required: true

jobs:
  test-ios:
    name: Test for iOS
    runs-on: macos-15-xlarge
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        if: ${{ !inputs.skip-everything }}
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
        if: ${{ !inputs.skip-everything }}
        with:
          for: ios-test
      - name: shared checks & unit tests
        if: ${{ !inputs.skip-everything }}
        run: ./gradlew shared:iosSimulatorArm64Test
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure() && !inputs.skip-everything
        with:
          name: ios-shared-reports
          path: shared/build/reports
      - name: Add build environment variables
        if: ${{ !inputs.skip-everything }}
        run: |
          {
            echo "export SENTRY_DSN=${SENTRY_DSN}"
            echo "export SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}"
            echo "export FIREBASE_KEY=${FIREBASE_KEY}"
            echo "export GOOGLE_APP_ID_IOS=${GOOGLE_APP_ID_IOS}"
          } >> .envrc
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ENVIRONMENT: staging
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
          GOOGLE_APP_ID_IOS: ${{ secrets.GOOGLE_APP_ID_IOS }}
      - name: Get latest two iOS versions
        if: ${{ !inputs.skip-everything }}
        id: ios_versions
        run: |
          DEVICES=$(xcrun simctl list devices | awk '/^-- iOS/ {v=$3; next} v && /iPhone/ {print $1, $2, $3, "("v")"; v=""}' | sort -r | awk -F'[(.]' '!seen[$1]++')
          LATEST_DEVICE=$(echo "$DEVICES" | head -n 1)
          echo "LATEST_DEVICE=$LATEST_DEVICE" >> $GITHUB_OUTPUT
      - name: Run emulator tests
        if: ${{ !inputs.skip-everything }}
        run: |
          bundle exec fastlane ios test \
            xcodebuild_formatter:"xcbeautify --quieter --is-ci --renderer github-actions" \
            device:"${IOS_DEVICE}"
        env:
          IOS_DEVICE: ${{ steps.ios_versions.outputs.LATEST_DEVICE }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure() && !inputs.skip-everything
        with:
          name: ios-ios-results
          path: fastlane/test_output/*
