package com.mbta.tid.mbta_app.utils

public enum class SharedString {
    BetaEarlyAccessNote,
    BetaSection,
    CommuterRailAndFerryTickets,
    Crash,
    DebugMode,
    FareInformation,
    FavoritesByStop,
    FeatureFlagsSection,
    ForceNotificationsBeta,
    MapDisplay,
    MTicketApp,
    Notifications,
    PrivacyPolicy,
    ResourcesSection,
    RouteSearch,
    SendAppFeedback,
    SettingsSection,
    SoftwareLicenses,
    StationAccessibilityInfo,
    SupportAccessibilityNote,
    SupportHours,
    SupportSection,
    TermsOfUse,
    TripPlanner,
    ViewSourceOnGithub,
}
